version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: room_matching_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 2004
      POSTGRES_DB: room_matching
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: room_matching_redis
    restart: unless-stopped
    ports:
      - '6379:6379'

volumes:
  postgres_data: